# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Latest Dev Build

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@859c33240bd026ce8d5f711f5adcc65c2f8eafc1
      - name: Build with Gradle
        uses: gradle/gradle-build-action@c3afc518f523c6beeaa2fa40732832488b171f1b
        with:
          arguments: makeDevZip
      - uses: actions/upload-artifact@v3
        with:
          name: Dev-CheddarBratWurst-Client
          path: build/CheddarBratWurst-Client-*

